name: lando-d9
recipe: drupal9
compose:
  - docker-compose.network-mtu.yml
config:
  webroot: .
  php: 8.1
services:
  appserver:
    ssl: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
