name: localgov-micro
recipe: drupal9
compose:
  - docker-compose.network-mtu.yml
config:
  webroot: .
  xdebug: false
  webroot: .
  php: '8.1'
services:
  appserver:
    ssl: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
database:
    creds:
      user: database
      password: database
      database: database      
